name: Build HydePHP Site

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Build the site
      run: php hyde build --no-api

    # Now that the site is built, there are a few options for deployment.
    # We could push directly to the gh-pages branch, commit files to /docs,
    # or even use the GitHub Pages action to deploy the compiled site.
    # We could also upload the site as an artifact for later use.

    - name: Commit changes
      uses: EndBug/add-and-commit@v9 
      with:
        add: 'docs'
        message: 'Build the site'
